### ISSUE TITLE
pdf: No config found

### ISSUE THREAD

**Issue by PerJensen** [ColdTrick/event_manager#153] opened 2019-10-28 04:40 UTC
When I try to "Save as pdf", I get the no config error. Bug or is there anything I need to configure for this to work?

**Comment by jdalsem** [comment] 2019-10-28 08:05
did you install the plugin via composer or downloaded the zip from github or elgg.org?

**Comment by PerJensen** [comment] 2019-10-28 08:20
From github, normal plugin install.

**Comment by jdalsem** [comment] 2019-10-28 08:52
unable to reproduce at the moment... did you download a release from github or just the latest code?

**Comment by PerJensen** [comment] 2019-10-28 10:12
Hmmm, probably with latest code. Just tried with latest release and it's working. Sorry.
(google maps still not working though)

**Comment by jdalsem** [comment] 2019-10-28 10:13
ok.. will close it then

**Closed by jdalsem** 2019-10-28 10:13 UTC
